### ISSUE TITLE
Does switch trigger open on init?

### ISSUE THREAD

**Issue by cballenar** [rsporny/homebridge-gpio-switch#4]
When I restart Homebridge, the pin signal goes off (and stays alive) even if the switch state in homekit is off.

Is the line below the cause? If so, any particular reason for it?

https://github.com/rsporny/homebridge-gpio-switch/blob/5548ec380f56843e60e20da48b6d51d14a013e81/index.js#L29

**Comment by rsporny** [comment]
Hi @cballenar,

Thanks for the PR, I've merged it.

To answer your question, some relays are activated by low state, but the invert logic was missing here, so thanks again for fixing.
